title = "ВетСкоуп"
baseURL = "https://example.zoo"
languageCode = "ru_RU"
theme = 'ananke'
resourceDir = "../resources"

DefaultContentLanguage = "ru"
SectionPagesMenu = "articles"
pagination.pagerSize = 3                  # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true

weight = 1
contentDir = "content/"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "Frickin' Zoo and all you need to know about animals."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3
main_section = "articles"


[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[menu]
  [[menu.main]]
    identifier = "knowledge-base"
    name = "База Снимков"
    url = "/knowledge-base/"
    weight = 1

  [[menu.main]]
    identifier = "articles"
    name = "Статьи"
    url = "/articles/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "О компании"
    url = "/about"
    weight = 3
