title = "ВЕТ КЛАУД"
baseURL = "https://noponyasked.github.io/vetscope/"
languageCode = "ru"
theme = "ananke"
resourceDir = "../resources"
DefaultContentLanguage = "ru"
SectionPagesMenu = "articles"
enableRobotsTXT = true
weight = 1
contentDir = "content/"
[pagination]
pagerSize = "10"
[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = ""
background_color_class = "bg-black"
recent_posts_number = 3
main_section = "articles"
[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"
[[menu.main]]
identifier = "knowledge-base"
name = "База Снимков"
url = "/knowledge-base/"
weight = 1
[[menu.main]]
identifier = "articles"
name = "Статьи"
url = "/articles/"
weight = 2
[[menu.main]]
identifier = "about"
name = "О компании"
url = "/about"
weight = 3
[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
